export const popularCourses = [
  {
    id: 1,
    title: "Python for Beginners",
    instructor: "John Miller",
    learners: "12K",
    rating: 4.8,
    duration: "8 hours",
    level: "Beginner",
    thumbnail: "🐍",
    price: "Free",
    category: "Programming",
  },
  {
    id: 2,
    title: "Advanced React Development",
    instructor: "Sarah Wilson",
    learners: "8.5K",
    rating: 4.9,
    duration: "12 hours",
    level: "Advanced",
    thumbnail: "⚛",
    price: "Free",
    category: "Web Development",
  },
  {
    id: 3,
    title: "Data Science Fundamentals",
    instructor: "Dr. Alex Kumar",
    learners: "15K",
    rating: 4.7,
    duration: "16 hours",
    level: "Intermediate",
    thumbnail: "📊",
    price: "Free",
    category: "Data Science",
  },
  {
    id: 4,
    title: "Digital Marketing Mastery",
    instructor: "Lisa Park",
    learners: "9.2K",
    rating: 4.6,
    duration: "10 hours",
    level: "Beginner",
    thumbnail: "📱",
    price: "Free",
    category: "Marketing",
  },
  {
    id: 5,
    title: "Digital Marketing Mastery",
    instructor: "Lisa Park",
    learners: "9.2K",
    rating: 4.6,
    duration: "10 hours",
    level: "Beginner",
    thumbnail: "📱",
    price: "Free",
    category: "Marketing",
  },
  {
    id: 6,
    title: "Python for Beginners",
    instructor: "John Miller",
    learners: "12K",
    rating: 4.8,
    duration: "8 hours",
    level: "Beginner",
    thumbnail: "🐍",
    price: "Free",
    category: "Programming",
  },
  {
    id: 7,
    title: "Advanced React Development",
    instructor: "Sarah Wilson",
    learners: "8.5K",
    rating: 4.9,
    duration: "12 hours",
    level: "Advanced",
    thumbnail: "⚛",
    price: "Free",
    category: "Web Development",
  },
  {
    id: 8,
    title: "Data Science Fundamentals",
    instructor: "Dr. Alex Kumar",
    learners: "15K",
    rating: 4.7,
    duration: "16 hours",
    level: "Intermediate",
    thumbnail: "📊",
    price: "Free",
    category: "Data Science",
  },
  {
    id: 9,
    title: "Digital Marketing Mastery",
    instructor: "Lisa Park",
    learners: "9.2K",
    rating: 4.6,
    duration: "10 hours",
    level: "Beginner",
    thumbnail: "📱",
    price: "Free",
    category: "Marketing",
  },
  {
    id: 10,
    title: "Digital Marketing Mastery",
    instructor: "Lisa Park",
    learners: "9.2K",
    rating: 4.6,
    duration: "10 hours",
    level: "Beginner",
    thumbnail: "📱",
    price: "Free",
    category: "Marketing",
  },
];
