export const featuredInstructors = [
  {
    id: 1,
    name: "Ava Lee",
    title: "Math Educator",
    followers: "45K",
    rating: 4.9,
    courses: 24,
    avatar: "👩‍🏫",
    specialty: "Advanced Mathematics",
    verified: true,
  },
  {
    id: 2,
    name: "Dr. Sarah Chen",
    title: "Computer Science",
    followers: "38K",
    rating: 4.8,
    courses: 18,
    avatar: "👩‍💻",
    specialty: "AI & Machine Learning",
    verified: true,
  },
  {
    id: 3,
    name: "Marcus Johnson",
    title: "Physics Expert",
    followers: "29K",
    rating: 4.9,
    courses: 31,
    avatar: "👨‍🔬",
    specialty: "Quantum Physics",
    verified: true,
  },
  {
    id: 4,
    name: "Elena Rodriguez",
    title: "Language Arts",
    followers: "42K",
    rating: 4.7,
    courses: 27,
    avatar: "👩‍🎓",
    specialty: "Creative Writing",
    verified: true,
  },

  {
    id: 5,
    name: "Ava Lee",
    title: "Math Educator",
    followers: "45K",
    rating: 4.9,
    courses: 24,
    avatar: "👩‍🏫",
    specialty: "Advanced Mathematics",
    verified: true,
  },
  {
    id: 6,
    name: "Dr. Sarah Chen",
    title: "Computer Science",
    followers: "38K",
    rating: 4.8,
    courses: 18,
    avatar: "👩‍💻",
    specialty: "AI & Machine Learning",
    verified: true,
  },
  {
    id: 7,
    name: "Marcus Johnson",
    title: "Physics Expert",
    followers: "29K",
    rating: 4.9,
    courses: 31,
    avatar: "👨‍🔬",
    specialty: "Quantum Physics",
    verified: true,
  },
  {
    id: 8,
    name: "Elena Rodriguez",
    title: "Language Arts",
    followers: "42K",
    rating: 4.7,
    courses: 27,
    avatar: "👩‍🎓",
    specialty: "Creative Writing",
    verified: true,
  },
];
