export const videoData = [
  {
    id: 1,
    title: "Mastering React in 2025: Complete Developer Guide",
    instructor: "Deepak Sharma",
    thumbnail: "https://img.youtube.com/vi/Tn6-PIqc4UM/maxresdefault.jpg",
    duration: "12:45",
    views: "1.2M",
    rating: 5,
    level: "Beginner",
    tags: ["React", "Frontend", "JavaScript", "Web Dev", "Hooks"],
  },
  {
    id: 2,
    title: "AI & Machine Learning Complete Roadmap for 2025",
    instructor: "Sarah Johnson",
    thumbnail: "https://img.youtube.com/vi/aircAruvnKk/maxresdefault.jpg",
    duration: "18:30",
    views: "875K",
    rating: 4,
    level: "Intermediate",
    tags: ["AI", "ML", "Python", "Roadmap", "TensorFlow"],
  },
  {
    id: 3,
    title: "Cloud Computing Crash Course: AWS to Azure",
    instructor: "Michael Lee",
    thumbnail: "https://img.youtube.com/vi/2LaAJq1lB1Q/maxresdefault.jpg",
    duration: "22:10",
    views: "650K",
    rating: 5,
    level: "Advanced",
    tags: ["Cloud", "AWS", "Azure", "DevOps", "Infrastructure"],
  },
  {
    id: 4,
    title: "Full Stack Web Development Masterclass",
    instructor: "Emma Rodriguez",
    thumbnail: "https://img.youtube.com/vi/Tn6-PIqc4UM/maxresdefault.jpg",
    duration: "15:20",
    views: "920K",
    rating: 4,
    level: "Intermediate",
    tags: ["Full Stack", "Node.js", "MongoDB", "Express"],
  },
  {
    id: 5,
    title: "Data Structures & Algorithms: Ultimate Coding Interview Prep",
    instructor: "Raj Patel",
    thumbnail: "https://img.youtube.com/vi/8hly31xKli0/maxresdefault.jpg",
    duration: "19:45",
    views: "1.8M",
    rating: 5,
    level: "Intermediate",
    tags: ["DSA", "Coding Interviews", "LeetCode", "Problem Solving"],
  },
  {
    id: 6,
    title: "Next.js 15 Crash Course: Building Scalable Apps",
    instructor: "Sophia Williams",
    thumbnail: "https://img.youtube.com/vi/mTz0GXj8NN0/maxresdefault.jpg",
    duration: "14:20",
    views: "720K",
    rating: 4,
    level: "Beginner",
    tags: ["Next.js", "React", "SSR", "Frontend", "Full Stack"],
  },
  {
    id: 7,
    title: "DevOps Roadmap 2025: Docker, Kubernetes & CI/CD",
    instructor: "David Kim",
    thumbnail: "https://img.youtube.com/vi/9zUHg7xjIqQ/maxresdefault.jpg",
    duration: "25:10",
    views: "1.1M",
    rating: 5,
    level: "Advanced",
    tags: ["DevOps", "Docker", "Kubernetes", "CI/CD", "Cloud"],
  },
  {
    id: 8,
    title: "Blockchain Development Bootcamp: From Basics to DApps",
    instructor: "Olivia Chen",
    thumbnail: "https://img.youtube.com/vi/gyMwXuJrbJQ/maxresdefault.jpg",
    duration: "21:00",
    views: "540K",
    rating: 4,
    level: "Intermediate",
    tags: ["Blockchain", "Ethereum", "Solidity", "Web3", "Smart Contracts"],
  },
  {
    id: 9,
    title: "Cybersecurity Essentials: Protecting Systems in 2025",
    instructor: "James Anderson",
    thumbnail: "https://img.youtube.com/vi/2zcyS5b5KXc/maxresdefault.jpg",
    duration: "16:35",
    views: "460K",
    rating: 5,
    level: "Beginner",
    tags: ["Cybersecurity", "Ethical Hacking", "Networking", "Security"],
  },
  {
    id: 10,
    title: "UI/UX Design Principles: Designing for the Future",
    instructor: "Maria Lopez",
    thumbnail: "https://img.youtube.com/vi/3Ywz0S3cSqs/maxresdefault.jpg",
    duration: "13:50",
    views: "385K",
    rating: 4,
    level: "Beginner",
    tags: ["UI/UX", "Design", "Figma", "Prototyping"],
  },
  {
    id: 11,
    title: "Python for Data Science: Pandas, Numpy & Visualization",
    instructor: "Ahmed Khan",
    thumbnail: "https://img.youtube.com/vi/r-uOLxNrNk8/maxresdefault.jpg",
    duration: "20:15",
    views: "1.3M",
    rating: 5,
    level: "Intermediate",
    tags: ["Python", "Data Science", "Pandas", "Numpy", "Visualization"],
  },
];
